jenkins:
  persistence:
    size: "50Gi"
  controller:
    resources:
      requests:
        cpu: "2000m"
        memory: "4096Mi"
      limits:
        cpu: "2000m"
        memory: "4096Mi"
    probes:
      livenessProbe:
        initialDelaySeconds: 150
      readinessProbe:
        initialDelaySeconds: 150
    enableRawHtmlMarkupFormatter: true
    image: "jenkins/jenkins"
    tag: "2.303.1-jdk11"
    jenkinsUrl: https://jenkinsgkewheel.tk/
    containerEnv:
      - name: BIND_PASSWORD
        valueFrom:
          secretKeyRef:
            name: ad-jenkinsldap-password
            key: password
      - name: VAULT_ADDRESS
        valueFrom:
          secretKeyRef:
            name: vault
            key: address
      - name: VAULT_TOKEN
        valueFrom:
          secretKeyRef:
            name: vault
            key: token
      - name: VAULT_PATH
        valueFrom:
          secretKeyRef:
            name: vault
            key: path

    JCasC:
      authorizationStrategy: |-
    installPlugins:
      - ace-editor
      - active-directory
      - amazon-ecr
      - ansicolor
      - ant
      - antisamy-markup-formatter
      - apache-httpcomponents-client-4-api
      - authentication-tokens
      - authorize-project
      - bouncycastle-api
      - branch-api
      - build-timeout
      - build-token-root
      - built-on-column
      - cloudbees-folder
      - command-launcher
      - conditional-buildstep
      - configuration-as-code
      - copyartifact
      - credentials
      - credentials-binding
      - display-url-api
      - docker-build-publish
      - docker-commons
      - docker-custom-build-environment
      - docker-workflow
      - durable-task
      - external-monitor-job
      - folder-auth
      - git
      - git-client
      - github
      - github-api
      - github-branch-source
      - git-server
      - google-container-registry-auth
      - google-oauth-plugin
      - greenballs
      - handlebars
      - hashicorp-vault-plugin
      - htmlpublisher
      - http_request
      - icon-shim
      - image-tag-parameter
      - jackson2-api
      - jacoco
      - javadoc
      - jdk-tool
      - jenkins-multijob-plugin
      - jobConfigHistory
      - job-dsl
      - jquery-detached
      - jsch
      - junit:latest
      - kubernetes
      - kubernetes-client-api
      - kubernetes-credentials
      - ldap
      - locale
      - lockable-resources
      - mailer
      - mapdb-api
      - matrix-auth
      - matrix-project
      - maven-plugin
      - momentjs
      - multiple-scms
      - node-iterator-api
      - oauth-credentials
      - pam-auth
      - parameterized-trigger
      - pegdown-formatter
      - pipeline-build-step
      - pipeline-github-lib
      - pipeline-graph-analysis
      - pipeline-input-step
      - pipeline-milestone-step
      - pipeline-model-api
      - pipeline-model-declarative-agent
      - pipeline-model-definition
      - pipeline-model-extensions
      - pipeline-rest-api
      - pipeline-stage-step
      - pipeline-stage-tags-metadata
      - pipeline-stage-view
      - pipeline-utility-steps
      - plain-credentials
      - pubsub-light
      - rebuild
      - resource-disposer
      - role-strategy
      - run-condition
      - scm-api
      - script-security
      - sse-gateway
      - ssh-credentials
      - ssh-slaves
      - structs
      - timestamper
      - token-macro
      - trilead-api
      - uno-choice
      - variant
      - windows-slaves
      - workflow-aggregator
      - workflow-api
      - workflow-basic-steps
      - workflow-cps
      - workflow-cps-global-lib
      - workflow-durable-task-step
      - workflow-job
      - workflow-multibranch
      - workflow-scm-step
      - workflow-step-api
      - workflow-support
      - ws-cleanup