apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-external-ingress
  labels:
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - jenkins.gke.gcp.tailoredbrands.com
    secretName: {{ .Release.Name }}-external-ssl
  rules:
  - host: jenkins.gke.gcp.tailoredbrands.com
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-master-ilb
          servicePort: 80